name: Security Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 2 * * 1' # Run weekly on Mondays at 2 AM UTC

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run dependency security audit
        run: pnpm audit --audit-level=moderate
        continue-on-error: true

      - name: Check for common security issues
        run: |
          echo "Checking for common security issues..."

          # Check for hardcoded secrets/passwords
          echo "Checking for potential hardcoded secrets..."
          if grep -r -i "password\s*=\s*['\"]" src/ --exclude-dir=node_modules || \
             grep -r -i "secret\s*=\s*['\"]" src/ --exclude-dir=node_modules || \
             grep -r -i "api_key\s*=\s*['\"]" src/ --exclude-dir=node_modules; then
            echo "WARNING: Potential hardcoded secrets found!"
            echo "Please review and use environment variables instead."
            exit 1
          else
            echo "PASS: No hardcoded secrets detected"
          fi

          # Check for console.log in production code (already handled in our standardization)
          echo "Checking for debug statements..."
          if find src/ -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" | \
             xargs grep -l "console\.log" | grep -v "__test__" | grep -v ".test."; then
            echo "INFO: Found console.log statements (these should be removed before production)"
          else
            echo "PASS: No debug statements found"
          fi

          # Check for TODO security items
          echo "Checking for security TODOs..."
          if grep -r -i "TODO.*security\|FIXME.*security\|TODO.*auth\|FIXME.*auth" src/ --exclude-dir=node_modules; then
            echo "INFO: Found security-related TODOs - please address these"
          else
            echo "PASS: No security TODOs found"
          fi

      - name: Build verification (security perspective)
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Security summary
        run: |
          echo "Security Check Summary:"
          echo "PASS: Dependency audit completed"
          echo "PASS: Hardcoded secrets check completed"
          echo "PASS: Debug statements check completed"
          echo "PASS: Security TODOs check completed"
          echo "PASS: Production build verification completed"
          echo ""
          echo "Security recommendations:"
          echo "1. Regularly update dependencies"
          echo "2. Use environment variables for all secrets"
          echo "3. Enable GitHub Dependabot alerts"
          echo "4. Consider adding rate limiting to API routes"
          echo "5. Implement proper input validation"

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: true
